options:
  repo:
    type: string
    default: "https://github.com/pavelpachkovskij/sample-rails.git"
    description: Application repository URL
  branch:
    type: string
    default: master
    description: Application branch name (git only).
  revision:
    type: string
    default: HEAD
    description: "The revision to be checked out. This can be symbolic, like HEAD or it can be a source control management-specific revision identifier. Default value: HEAD (svn only)."
  scm_provider:
    type: string
    default: git
    description: The name of the source control management provider to be used (git or svn).
  deploy_key:
    type: string
    default: ""
    description: A deploy key is an SSH key that is stored on the server and grants access to a repository (git only).
  svn_username:
    type: string
    default: ""
    description: The password for the user that has access to the Subversion repository (svn only).
  svn_password:
    type: string
    default: ""
    description: The user name for a user that has access to the Subversion repository (svn only).
  rack_env:
    type: string
    default: production
    description: Both RACK_ENV and RAILS_ENV environment variables.
  extra_packages:
    type: string
    default: ""
    description: Extra packages to install before bundle install
  command:
    type: string
    default: nil
    description: A command to run in the application root.
  port:
    type: int
    default: 80
    description: Port to run application