options:
  app_name:
    type: string
    default: sample-rails
    description: Application Name
  repo_url:
    type: string
    default: "https://github.com/pavelpachkovskij/sample-rails.git"
    description: Application repository URL
  repo_branch:
    type: string
    default: master
    description: Application branch name (git only, for bzr the branch is in the url)
  repo_type:
    type: string
    default: git
    description: Repository type {git|bzr|svn} for now
  install_root:
    type: string
    default: /var/www
    description: Install the application in app_name under this directory
  extra_packages:
    type: string
    default: ""
    description: Extra packages to install before bundle install
  port:
    type: int
    default: 80
    description: Port to run application
  migrate_database:
    type: boolean
    default: true
    description: Migrate database
  seed_database:
    type: boolean
    default: true
    description: Seed database
  compile_assets:
    type: boolean
    default: true
    description: Compile assets