#!/bin/bash
set -e

export HOME=/root

apt-get update
apt-get install -y curl build-essential

curl -L https://get.rvm.io | bash -s stable --ruby

export PATH=$PATH:/usr/local/rvm/bin
source /usr/local/rvm/scripts/rvm

cd "$(dirname $0)" && bundle install

configure_chef_solo() {
  cat > /etc/chef/solo.rb <<EOF
  cookbook_path '$(dirname $0)/chef/cookbooks'
EOF
}

mkdir -p /etc/chef
[[ -a /etc/chef/solo.rb ]] || configure_chef_solo()